### PR TITLE
Update behaviour for `immutable` and `computed` properties

### PR DESCRIPTION
**Pull request by yvo-niedrich**
## OpenAPI Documentation
 - Display `computed` properties in the Create-OpenApi, if it is also annotated as `ComputedDefaultValue`
 - Hide `immutable` properties in the Update-OpenApi
 - Include `GeneratedProperties` (in addition to `Declared`) when generating the Entity OpenAPI documentation

## Property Filtering
 - Strips `computed` fields from create operations, unless the property is also annotated as `ComputedDefaultValue`
 - Strips `computed` fields from update operations

## Annotations
 - `Enum` can be annotated as `nullable` and `immutable`

## Changes
 - Default drivers key properties (with a default value) are annotated as `Computed` - instead of `ComputedDefault`
 - `Guid` properties are properly validated (thanks @sean-james-eco)

## Bugfixes
 - Initialise the `$cookie` property of a request when converting `Illuminate\Request`. Fixes `"Request::$cookies must not be accessed before initialization"` when Telescope and APP_DEBUG are enabled.
 - `EloquentEntitySet::create` complies with `attribute.source` for navigation source (thanks @sean-james-eco)
 - Prevent deprecation warnings during `boot` with Laravel 11.x

### CODE REVIEW

**Comment by yvo-niedrich** [comment]
Rollback on the last commit... Going on holidays for a couple of days, I'll deal with exposing Generated Properties via OpenAPI next week: The tests fail because snapshots don't match. I'm not too comfortable with this, but in case you want to take a look at that here's the a patch of the code changes.

Meanwhile I'd be very much obliged if the above changes could be approved :)


[GeneratedProperties_in_OpenAPI_Schema.patch](https://github.com/user-attachments/files/16281110/GeneratedProperties_in_OpenAPI_Schema.patch)

**Comment by yvo-niedrich** [comment]
Found the `docker` command to boot up mongo - all test snapshots are updated now: `Generated` properties are listed in the OpenAPI documentation when describing an Entity.

Ready for merge (in my opinion)

**Comment by 27pchrisl** [comment]
Hi @yvo-niedrich, thanks for the work! On the computed default properties I'm not sure it's correct to indicate those can be provided during a create operation, as they are still computed by the server and not the client?

**Comment by 27pchrisl** [comment]
Ah, no you're right, "A value for this property can be provided by the client on insert and update. If no value is provided on insert, a non-static default value is generated"

**Comment by 27pchrisl** [comment]
and in that case, the entity set drivers right now are incorrectly annotating with `Computed`, not `ComputedDefaultValue` - would you mind making that change as part of this?

**Comment by yvo-niedrich** [comment]
Ah, I believe I see what you mean. [This](https://github.com/flat3/lodata/blob/5.x/tests/Drivers/WithNumericCollectionDriver.php#L25) one for example - right?

I'll go ahead and completely separate `Computed` from `ComputedDefault` in the types then... Will do tomorrow.

**Comment by 27pchrisl** [comment]
In https://github.com/flat3/lodata/blob/be527e5a941fb4f9640778446002981823daed19/src/Drivers/EloquentEntitySet.php#L680
and https://github.com/flat3/lodata/blob/be527e5a941fb4f9640778446002981823daed19/src/Drivers/CSVEntityType.php#L21 for example, the standard drivers should be using `Computed` here.

**Comment by yvo-niedrich** [comment]
Had some time to spare and updated the PR already 🙈 

I've also included another change (again thanks to @sean-james-eco) to properly validate UUIDs. Now a 400 error is returned - instead of the DatabaseException (HTTP 500) when the Eloquent Driver tries to write an invalid value to the database.

**Comment by yvo-niedrich** [comment]
Hey @27pchrisl are we still missing some of the updates you mentioned? I thought I caught them all 🤔

**Comment by 27pchrisl** [comment]
@yvo-niedrich Nope! I just hadn't got round to reading all the changes : ) I'll tag shortly...

**Pull request merged**
